Repository pagopa/pagopa-ecommerce-watchdog-deadletter-fe, pull requests merged in 2025-09, with the labels that each got.

#2 docs: Update README.md file and package.json
  README.md
  package.json
Labels: documentation

#3 Fix token read only once
  src/app/page.tsx
  src/app/utils/utils.ts
Labels: bug

#5 PIDM-941: refactor metrics charts to component
  src/app/ChartsStatistics.tsx
  src/app/page.tsx
Labels: enhancement

#6 chore(transactions-table): PIDM-942 refactor transactions table to component
  src/app/TransactionsTable.tsx
  src/app/page.tsx
Labels: enhancement

#8 chore(utils): PIDM-958 Utils refactoring
  src/app/page.tsx
  src/app/utils/api/client.ts
  src/app/utils/utils.ts
Labels: enhancement

#14 PIDM 965: add unit test pipe and jest
  .devops/code-review-pipelines.yml
  .gitignore
  jest.config.ts
  package.json
  src/app/TransactionsTable.tsx
  src/app/__tests__/SampleTest.test.tsx
  src/app/page.tsx
  yarn.lock
Labels: bug

#17 feat(PIDM-1000): Add helm files
  helm/.helmignore
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
Labels: enhancement
